In [ ]:
from sentence_transformers import SentenceTransformer # Focuses on meaning and context of the sentences. It is designed to capture the overall meaning of the sentences, including the relationships between words and the context in which they are used.
model = SentenceTransformer('all-MiniLM-L6-v2') # the model is defined here. This model is already trained on huge amounts of text.

# model becomes an object that can do things like encode sentences, compute embeddings, compare similarities

# Sentences to be encoded
sentences = [
    "Virat Kohli is a great cricketer.",
    "Sachin Tendulkar is a great cricketer."
]
embeddings = model.encode(sentences)


Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9899.25it/s]


In [ ]:
embeddings.shape # The shape of the embeddings is (2, 384) because we have 2 sentences and each sentence is represented by a 384-dimensional vector.

(2, 384)

In [14]:
embeddings

array([[ 4.67291698e-02,  6.60390779e-02, -5.60898073e-02,
        -4.77218628e-02,  6.72906777e-03,  5.84863015e-02,
         8.23954567e-02,  3.61136161e-02, -2.76420750e-02,
         2.49764752e-02,  2.17825989e-03, -7.35368431e-02,
         4.51484621e-02,  1.00616761e-01,  8.97640064e-02,
         1.13054821e-02,  6.22827150e-02,  5.29906638e-02,
         1.75350588e-02, -6.07292913e-02, -7.93454126e-02,
         1.08952977e-01,  3.86260860e-02, -2.02276036e-02,
        -3.68788652e-02, -5.12867719e-02, -3.60485283e-03,
         5.15539683e-02,  3.52186412e-02,  1.49401044e-02,
         1.86774209e-02,  3.17733325e-02, -6.60781637e-02,
         7.36771151e-02, -5.42628914e-02,  7.18715228e-03,
        -5.39370812e-02,  1.11398578e-01,  7.13963062e-02,
        -5.39923944e-02, -3.25294212e-02,  2.62484374e-03,
         9.36954934e-03,  2.49193888e-02,  3.20181102e-02,
         4.03161813e-03, -8.63915123e-03, -1.08779385e-03,
        -2.56298799e-02,  5.10986836e-04, -6.20200597e-0

In [15]:
similarity=model.similarity(embeddings,embeddings)
similarity # depicts the similarity between the two sentences. The value will be between 0 and 1, where 1 means the sentences are identical and 0 means they are completely different.

tensor([[1.0000, 0.7818],
        [0.7818, 1.0000]])

In [16]:
from sentence_transformers import CrossEncoder
model = CrossEncoder('cross-encoder/stsb-roberta-base') # this model is trained to compute the similarity between two sentences. It takes two sentences as input and outputs a similarity score between 0 and 1.

# We want to compute the similarity between the query sentence...
query = "A man is eating pasta."

# ... and all sentences in the corpus
corpus = [
    "A man is eating food.",
    "A man is eating a piece of bread.",
    "The girl is carrying a baby.",
    "A man is riding a horse.",
    "A woman is playing violin.",
    "Two men pushed carts through the woods.",
    "A man is riding a white horse on an enclosed ground.",
    "A monkey is playing drums.",
    "A cheetah is running behind its prey.",
]

ranks=model.rank(query, corpus) # this will compute the similarity between the query and each sentence in the corpus and return the ranks of the sentences in the corpus based on their similarity to the query.

c:\Users\milin\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\milin\.cache\huggingface\hub\models--cross-encoder--stsb-roberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 7165.42it/s]


In [ ]:
ranks # the output will be a list of indices that represent the ranks of the sentences in the corpus based on their similarity to the query. The index 0 corresponds to the most similar sentence, index 1 corresponds to the second most similar sentence, and so on.

[{'corpus_id': 0, 'score': 0.6559632},
 {'corpus_id': 1, 'score': 0.37253082},
 {'corpus_id': 3, 'score': 0.061946057},
 {'corpus_id': 6, 'score': 0.05221325},
 {'corpus_id': 5, 'score': 0.0023319954},
 {'corpus_id': 2, 'score': 0.0023199355},
 {'corpus_id': 8, 'score': 0.0022599634},
 {'corpus_id': 7, 'score': 0.0022426567},
 {'corpus_id': 4, 'score': 0.0021998682}]

In [ ]:
from sentence_transformers import SparseEncoder # Focuses on words present in the input sentences and ignores the rest. It is designed to capture the most important features of the sentences while discarding less relevant information.
model = SparseEncoder("naver/splade-cocondenser-ensembledistil") # this model is trained to compute the similarity between two sentences using sparse representations. It takes two sentences as input and outputs a similarity score between 0 and 1.

c:\Users\milin\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\milin\.cache\huggingface\hub\models--naver--splade-cocondenser-ensembledistil. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 204/204 [00:00<00:00, 41012.22it/s]


In [19]:
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]

embeddings = model.encode(sentences) # this will compute the sparse embeddings for the given sentences. The output will be a list of sparse vectors, where each vector represents the corresponding sentence in the input list.
embeddings

tensor(indices=tensor([[    0,     0,     0,     0,     0,     0,     0,     0,
                            0,     0,     0,     0,     0,     0,     0,     0,
                            0,     0,     0,     0,     0,     0,     0,     0,
                            0,     0,     0,     0,     0,     0,     0,     0,
                            0,     0,     0,     0,     0,     0,     0,     0,
                            0,     0,     0,     0,     0,     1,     1,     1,
                            1,     1,     1,     1,     1,     1,     1,     1,
                            1,     1,     1,     1,     1,     1,     1,     1,
                            1,     1,     1,     1,     1,     1,     1,     1,
                            1,     1,     1,     1,     1,     1,     1,     1,
                            1,     1,     1,     1,     1,     1,     1,     1,
                            1,     1,     2,     2,     2,     2,     2,     2,
                            2,     2,   

In [20]:
embeddings.shape # The shape of the embeddings will depend on the specific implementation of the SparseEncoder model.

torch.Size([3, 30522])

In [21]:
similarity = model.similarity(embeddings, embeddings) # this will compute the similarity between the sparse embeddings of the sentences. The output will be a matrix of similarity scores, where each entry (i, j) represents the similarity between the i-th and j-th sentences in the input list.
similarity

tensor([[3.5629e+01, 9.1541e+00, 9.8059e-02],
        [9.1541e+00, 2.7478e+01, 1.9061e-02],
        [9.8059e-02, 1.9061e-02, 2.9553e+01]])

In [23]:
stats=SparseEncoder.sparsity(embeddings) # this will compute the sparsity of the embeddings. The output will be a list of sparsity values, where each value represents the sparsity of the corresponding embedding in the input list.
stats # the output will be a list of sparsity values, where each value represents the spars

{'active_dims': 49.66666793823242, 'sparsity_ratio': 0.9983727584057981}